### PR TITLE
"Advanced Player Links" Plugin added

### PR DESCRIPTION
**Pull request by I-MrFixIt-I**
I rewrote the plugin "Advanced Player Links" (https://getbblog.com/en/user/messages?thread=156701) to the new Greaterfield

### CODE REVIEW

**Comment by brainfoolong** [comment]
Thx, merged.

**Comment by brainfoolong** [comment]
I recommend using `gf.frontend.getCurrentPersona()` for current logged in user information. That contains name, platform and id. For me the links don't work.

**Comment by brainfoolong** [comment]
Nevermind, this always returns me, and not the profile i view :)

**Comment by I-MrFixIt-I** [comment]
hmm well, nvm.
Yeah, I already realised that the links are not working correctly. I'm just wondering why. Because when I run just the script in the console the links are working fine..... While writing this I may got an idea why it's not working ^^

**Pull request merged**
